### ISSUE TITLE
Unable to compile influxdb on centos

### ISSUE THREAD

**Issue by snortingbull** [influxdb/influxdb#4539]
Using go 1.4.2
I am unable to compile on centOS 
Following is the error : 
root@b6721e5d4fc0 influxdb]# go get ./...
##github.com/influxdb/influxdb/tsdb
influxdb/tsdb/functions.go:1318: undefined: strings.Compare

Used following commands : 

go get github.com/influxdb/influxdb
cd $GOPATH/src/github.com/influxdb/
go get ./...
go install ./...

**Comment by otoolep** [comment]
As explained in the CONTRIBUTING docs, you must build with Go 1.5.
